this fixes all nightly tests
./src/drt_f2/fluid2_line_evaluate.cpp:998: error: ISO C++ forbids variable-size array 'intpointinparent'

"-pedantic" compiler switch figured that it's not standard conforming to have a C array with variable sizes -> replaced with std::vector (could be Blitz or Epetra matrices as well)

Note: the parallel BACI version has no pedantic switch, since the MPI header (mpi.h) is - at least the compiler says so - not C++ standard conforming! Hence one will bump into this from time to time when one develops only with the parallel BACI version.
I'll fix it for you, since I introduced and insisted on this pedantry... ;-)

This extra burden hopefully pays of when using different compilers/compiler versions/CPUs...

PS: now you also know who is still sequential / yesterday


git-svn-id: svn://jacobi.lnm.mw.tum.de/baci/trunk/ccarat@7183 060e22d8-9d1c-0410-868a-e3a950d63d95